name: Jenkins

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Compose file
      - name: Create Docker Compose File
        run: |
          echo "
          version: '3.8'
          services:
            jenkins:
              image: jenkins/jenkins:lts
              container_name: jenkins
              ports:
                - '8080:8080'
                - '50000:50000'
              volumes:
                - jenkins_home:/var/jenkins_home
              restart: always
              environment:
                JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
            
            
 # Step 4: Install Ngrok
      - name: Install Ngrok
        run: |
          sudo apt-get install unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      # Step 5: Install jq to parse JSON
      - name: Install jq
        run: sudo apt-get install jq

      # Step 6: Authenticate Ngrok
      - name: Authenticate Ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      # Step 7: Run Ngrok to expose InfluxDB port 8086
      - name: Expose InfluxDB using Ngrok
        run: |
          nohup ngrok http 8086 &
          sleep 20  # Increased sleep time to allow InfluxDB to fully initialize

      # Step 8: Fetch Ngrok public URL
      - name: Fetch Ngrok public URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url")
          echo "Your public InfluxDB URL is: $NGROK_URL"
          sleep 21600

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
