name: Jenkins with Ngrok CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Docker and Docker Compose
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify the installation

      # Step 3: Set up Docker Compose file
      - name: Create Docker Compose File
        run: |
          echo "
          version: '3.8'
          services:
            jenkins:
              image: jenkins/jenkins:lts
              container_name: jenkins
              ports:
                - '8080:8080'
                - '50000:50000'
              volumes:
                - jenkins_home:/var/jenkins_home
              restart: always
              environment:
                JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
          " > docker-compose.yml

      # Step 4: Start Jenkins using Docker Compose
      - name: Start Jenkins
        run: docker-compose up -d

      # Step 5: Install Ngrok
      - name: Install Ngrok
        run: |
          sudo apt-get install unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      # Step 6: Install jq to parse JSON
      - name: Install jq
        run: sudo apt-get install jq

      # Step 7: Authenticate Ngrok
      - name: Authenticate Ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      # Step 8: Run Ngrok to expose Jenkins port 8080
      - name: Expose Jenkins using Ngrok
        run: |
          nohup ngrok http 8080 &
          sleep 20  # Allow time for Jenkins and Ngrok to fully initialize

      # Step 9: Fetch Ngrok public URL
      - name: Fetch Ngrok public URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url")
          echo "Your public Jenkins URL is: $NGROK_URL"
          sleep 21600

      # Step 10: Stop Docker Compose
      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
