name: Jenkins with Ngrok CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Compose file
      - name: Create Docker Compose File
        run: |
          echo "
          version: '3.8'
          services:
            jenkins:
              image: jenkins/jenkins:lts
              container_name: jenkins
              ports:
                - '8080:8080'
                - '50000:50000'
              volumes:
                - jenkins_home:/var/jenkins_home
              restart: always
              environment:
                JAVA_OPTS: '-Djenkins.install.runSetupWizard=false'
            
            ngrok:
              image: ngrok/ngrok:latest
              container_name: ngrok
              depends_on:
                - jenkins
              command: http jenkins:8080
              environment:
                NGROK_AUTHTOKEN: '${{ secrets.NGROK_AUTH_TOKEN }}'
              restart: always
            
          volumes:
            jenkins_home:
          " > docker-compose.yml

      # Step 3: Start Docker Compose services
      - name: Start Jenkins and Ngrok
        run: docker-compose up -d

      # Step 4: Wait for services to initialize
      - name: Wait for Jenkins and Ngrok
        run: sleep 30

      # Step 5: Fetch Ngrok public URL
      - name: Fetch Ngrok Public URL
        run: |
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' | tee ngrok_url.txt
          echo "Ngrok public URL for Jenkins: $(cat ngrok_url.txt)"

      # Step 6: Stop Docker Compose services (optional cleanup)
      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
